'use client';
import { useEffect, useState } from 'react';
import Link from 'next/link';
import { ArrowUpRightIcon } from '@heroicons/react/24/outline';
import { api, formatNumber } from '@/lib/api';
import { PageHeading } from '@/components/page-heading';
import { Empty, ErrorState, Loading } from '@/components/states';

type Metrics={received:number;executed:number;pending:number;ready_to_dispatch:number;outstanding_quantity:number;stock?:Record<string,number>};
type Dashboard={sections:Record<string,Metrics>;production:Record<string,number>;generated_at:string};
const cards=[['mds_outright','MDS Outright','Outright wholesale orders'],['mds_consignment','MDS Consignment','Stock placed with MDS'],['direct','Direct Clients','Independent client orders']] as const;

export default function Dashboard(){const [data,setData]=useState<Dashboard>();const [error,setError]=useState('');const [period,setPeriod]=useState('month');const load=()=>api<Dashboard>(`/dashboard?period=${period}`).then(setData).catch(e=>setError(e.message));useEffect(()=>{void load()},[period]);return <>
  <PageHeading eyebrow="Command center" title="Operations overview" description="Live order, production and stock position from the operations database." action={<select className="field !w-auto text-sm" value={period} onChange={e=>setPeriod(e.target.value)}><option value="today">Today</option><option value="week">This week</option><option value="month">This month</option><option value="all">All time</option></select>}/>
  {error?<ErrorState message={error} retry={load}/>:!data?<Loading/>:<><div className="grid xl:grid-cols-3 gap-5">{cards.map(([key,title,subtitle],index)=><section className={`card p-6 min-h-[330px] ${index===2?'xl:ml-2':''}`} key={key}><div className="flex justify-between"><div><div className="eyebrow">{index<2?'MDS':'Direct'}</div><h2 className="font-display text-2xl mt-2">{title}</h2><p className="text-xs text-stone-500 mt-1">{subtitle}</p></div><span className="w-2 h-2 mt-2 rounded-full bg-emerald-600"/></div><div className="mt-7 divide-y divide-stone-200">{[['Orders received','received'],['Orders executed','executed'],['Orders pending','pending'],['Ready to dispatch','ready_to_dispatch'],['Outstanding pieces','outstanding_quantity']].map(([label,metric])=><Link href={`/orders?order_type=${key}&metric=${metric}`} key={metric} className="flex items-center justify-between py-3.5 group"><span className="text-sm text-stone-600 group-hover:text-ink">{label}</span><span className="flex items-center gap-2 font-display text-xl">{formatNumber(data.sections[key]?.[metric as keyof Metrics] as number)}<ArrowUpRightIcon className="w-3.5 text-stone-400"/></span></Link>)}</div></section>)}</div><section className="mt-7"><div className="flex justify-between mb-4"><div><div className="eyebrow">Production floor</div><h2 className="font-display text-2xl mt-1">Pieces by current stage</h2></div><Link href="/production" className="text-xs underline underline-offset-4">Open queue</Link></div><div className="grid grid-cols-2 md:grid-cols-4 xl:grid-cols-7 gap-3">{Object.entries(data.production).map(([stage,count])=><Link href={`/production?current_stage=${stage}`} className="card p-4 hover:border-gold transition" key={stage}><div className="font-display text-3xl">{formatNumber(count)}</div><div className="text-[10px] mt-2 uppercase tracking-wider text-stone-500">{stage.replaceAll('_',' ')}</div></Link>)}</div></section></>}
  {!error&&data&&Object.values(data.sections).every(x=>x.received===0)&&<div className="mt-7"><Empty title="No operational records yet" detail="The dashboard is correctly showing an empty database. Create clients and products, then enter or convert a purchase order."/></div>}
</>}
