'use client';
import { useCallback, useEffect, useState } from 'react';
import Link from 'next/link';
import { useRouter, useSearchParams } from 'next/navigation';
import { api } from '@/lib/api';
import { PageHeading } from '@/components/page-heading';
import { Empty, ErrorState, Loading } from '@/components/states';
import { AuthDownload } from '@/components/auth-download';
import { OperationalListPage, orderColumns } from '@/components/operational-list-page';

function LinesheetPOs({linesheetId,requestedOrderId}:{linesheetId:string;requestedOrderId:string}){
  const [sheet,setSheet]=useState<any>(); const [order,setOrder]=useState<any>(); const [folder,setFolder]=useState<any>(); const [documents,setDocuments]=useState<any[]>([]); const [error,setError]=useState(''); const [message,setMessage]=useState(''); const [loading,setLoading]=useState(true); const [uploading,setUploading]=useState(false);
  const load=useCallback(async()=>{setLoading(true);setError('');try{const detail=await api<any>(`/linesheets/${linesheetId}`);setSheet(detail.linesheet);const linkedId=detail.related_order?._id||'';if(requestedOrderId&&linkedId&&requestedOrderId!==linkedId)throw new Error('The requested order is not associated with this linesheet.');if(String(detail.linesheet.type||'').startsWith('mds_')){const result=await api<any>(`/linesheets/${linesheetId}/purchase-orders`);setFolder(result.folder);setOrder(result.order);setDocuments(result.items||[])}else if(linkedId){const result=await api<any>(`/orders/${linkedId}`);setOrder(result.order);setDocuments(result.documents||[]);setFolder(undefined)}else{setOrder(undefined);setFolder(undefined);setDocuments([])}}catch(e){setError(e instanceof Error?e.message:'Unable to load purchase orders')}finally{setLoading(false)}},[linesheetId,requestedOrderId]);
  useEffect(()=>{void load()},[load]);
  const eligible=String(sheet?.type||'').startsWith('mds_');
  async function upload(files:FileList|null){if(!files?.length||(!eligible&&!order))return;setUploading(true);setError('');setMessage('');try{if(eligible){const form=new FormData();Array.from(files).forEach(file=>form.append('files',file));await api(`/linesheets/${linesheetId}/purchase-orders`,{method:'POST',body:form})}else{for(const file of Array.from(files)){const form=new FormData();form.append('file',file);await api(`/orders/${order._id}/documents`,{method:'POST',body:form})}}setMessage(`${files.length} purchase order${files.length===1?'':'s'} uploaded.`);await load()}catch(e){setError(e instanceof Error?e.message:'Unable to upload purchase orders')}finally{setUploading(false)}}
  if(loading)return <Loading/>; if(error&&!sheet)return <ErrorState message={error} retry={load}/>;
  const canUpload=eligible||Boolean(order); const title=folder?.display_name||sheet?.name||sheet?.linesheet_number||'Purchase-order documents';
  return <><PageHeading eyebrow="Documents · Purchase orders" title={title} description={order?`Linked order ${order.po_number} · ${order.client_name}`:eligible?'MDS linesheet PO folder · available before order conversion':'This RKFUPL linesheet has not been linked to an order yet.'} action={<Link className="button button-secondary" href={`/linesheets/${linesheetId}`}>Back to Linesheet</Link>}/>{message&&<div className="card alert-success mb-5">{message}</div>}{error&&<div className="card alert-error mb-5">{error}</div>}{canUpload?<><div className="card p-5 mb-6 flex flex-col md:flex-row md:items-center gap-4"><div className="flex-1"><div className="eyebrow">PO folder</div><div className="font-semibold mt-1">{folder?.display_name||order?.po_number}</div></div><label className="button cursor-pointer">{uploading?'Uploading…':'Upload PO'}<input className="hidden" type="file" accept="application/pdf,.pdf" multiple disabled={uploading} onChange={e=>void upload(e.target.files)}/></label></div>{documents.length?<div className="table-wrap"><table><thead><tr><th>Filename</th><th>Order reference</th><th>Uploaded</th><th>Version</th><th>Actions</th></tr></thead><tbody>{documents.map(doc=><tr key={doc._id}><td className="font-semibold">{doc.original_name}</td><td>{order?.po_number||'Awaiting order'}</td><td>{new Date(doc.created_at).toLocaleString()}</td><td>{doc.version||1}</td><td><div className="flex gap-3"><AuthDownload path={`/documents/${doc._id}/download?preview=true`} filename={doc.original_name} label="View" className="text-xs underline"/><AuthDownload path={`/documents/${doc._id}/download`} filename={doc.original_name} label="Download" className="text-xs underline"/></div></td></tr>)}</tbody></table></div>:<Empty title="No purchase orders" detail="Upload the first PDF to this linesheet folder."/>}</>:<div className="card p-6"><h2 className="font-display text-2xl">Order required</h2><p className="text-sm text-stone-600 mt-2">RKFUPL linesheets keep the existing order-based PO workflow. Convert this linesheet to an order before uploading documents.</p></div>}</>;
}

function GeneralPurchaseOrders(){const router=useRouter();const [sheets,setSheets]=useState<any[]>([]);const [selected,setSelected]=useState('');useEffect(()=>{api<any>('/linesheets?limit=100').then(result=>setSheets((result.items||[]).filter((item:any)=>String(item.type||'').startsWith('mds_')))).catch(()=>setSheets([]))},[]);return <><div className="card p-5 mb-6 flex flex-col md:flex-row gap-3 md:items-end"><label className="flex-1 text-sm font-semibold">Upload against an MDS linesheet<select className="field mt-2" value={selected} onChange={e=>setSelected(e.target.value)}><option value="">Select MDS linesheet</option>{sheets.map(sheet=><option key={sheet._id} value={sheet._id}>{sheet.name||sheet.linesheet_number}</option>)}</select></label><button className="button" disabled={!selected} onClick={()=>router.push(`/documents/purchase-orders?linesheetId=${selected}`)}>Open PO folder</button></div><OperationalListPage eyebrow="Documents" title="Purchase-order documents" description="Open a purchase order to upload, preview, download or review retained PDF versions." endpoint="/orders" columns={orderColumns} emptyTitle="No purchase orders" relatedHref="/sales/po-lookup" relatedLabel="PO lookup"/></>}

export default function Page(){const params=useSearchParams();const linesheetId=params.get('linesheetId')||'';const orderId=params.get('orderId')||'';return linesheetId?<LinesheetPOs linesheetId={linesheetId} requestedOrderId={orderId}/>:<GeneralPurchaseOrders/>}
