'use client';
import { FormEvent, useEffect, useState } from 'react';
import Link from 'next/link';
import { useParams, useRouter } from 'next/navigation';
import { api } from '@/lib/api';
import { PageHeading } from '@/components/page-heading';
import { ErrorState, Loading } from '@/components/states';
import { AuthDownload } from '@/components/auth-download';
import { LinesheetEditor } from '@/components/linesheet-editor';

export default function Page(){
  const {id}=useParams<{id:string}>(); const router=useRouter();
  const [data,setData]=useState<any>(); const [error,setError]=useState(''); const [editing,setEditing]=useState(false); const [message,setMessage]=useState(''); const [emailOpen,setEmailOpen]=useState(false); const [emailError,setEmailError]=useState(''); const [sending,setSending]=useState(false);
  const load=()=>api<any>(`/linesheets/${id}`).then(setData).catch(e=>setError(e.message)); useEffect(()=>{void load()},[id]);
  async function status(value:string){await api(`/linesheets/${id}`,{method:'PATCH',body:JSON.stringify({status:value})});load()}
  async function duplicate(){const result=await api<{id:string}>(`/linesheets/${id}/duplicate`,{method:'POST'});router.push(`/linesheets/${result.id}`)}
  async function remove(){if(!confirm('Delete this draft linesheet?'))return;await api(`/linesheets/${id}`,{method:'DELETE'});router.push('/linesheets')}
  async function share(e:FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget);await api(`/linesheets/${id}/share`,{method:'POST',body:JSON.stringify({recipient:f.get('recipient')})});setMessage('Share recipient recorded.');load()}
  async function email(e:FormEvent<HTMLFormElement>){e.preventDefault();setSending(true);setEmailError('');const f=new FormData(e.currentTarget);try{await api(`/linesheets/${id}/email`,{method:'POST',body:JSON.stringify({to:f.get('to'),cc:f.get('cc'),bcc:f.get('bcc'),subject:f.get('subject'),body:f.get('body'),attachments:f.get('attachments'),request_id:crypto.randomUUID()})});setMessage('Email sent successfully.');setEmailOpen(false)}catch(err:any){setEmailError(err.message)}finally{setSending(false)}}
  if(error)return <ErrorState message={error}/>; if(!data)return <Loading/>; const s=data.linesheet;
  if(editing)return <><PageHeading eyebrow="Draft editor" title={s.name} description={`${s.linesheet_number} · ${s.collection}`} action={<button className="button button-secondary" onClick={()=>setEditing(false)}>Cancel editing</button>}/><LinesheetEditor initial={s}/></>;
  return <><PageHeading eyebrow={`${s.collection} · Internal linesheet`} title={s.name||s.linesheet_number} description={`${s.linesheet_number} · ${s.items?.length||0} product configurations · ${s.status}`} action={<Link className="button button-secondary" href="/linesheets">← All linesheets</Link>}/>{message&&<div className="card alert-success">{message}</div>}
    <div className="flex flex-wrap gap-2 mb-6">{s.status==='draft'&&<button className="button" onClick={()=>setEditing(true)}>Edit draft</button>}<Link className="button" href={`/linesheets/${id}/view`}>View Linesheet</Link><AuthDownload path={`/linesheets/${id}/export.pdf`} filename={`${s.linesheet_number}.pdf`} label="Export PDF"/><Link className="button button-secondary" href={`/linesheets/${id}/preview`}>View Excel</Link><AuthDownload path={`/linesheets/${id}/export.xlsx`} filename={`${s.linesheet_number}.xlsx`} label="Export Excel"/><button className="button button-secondary" onClick={()=>setEmailOpen(true)}>Email linesheet</button><Link className="button button-secondary" href={`/documents/purchase-orders?linesheetId=${id}${data.related_order?`&orderId=${data.related_order._id}`:''}`}>View POs</Link><button className="button button-secondary" onClick={duplicate}>Duplicate</button>{s.status==='draft'&&<button className="button button-secondary" onClick={()=>status('confirmed')}>Confirm linesheet</button>}{s.status==='draft'&&!data.related_order&&<button className="button button-danger" onClick={remove}>Delete draft</button>}</div>
    {emailOpen&&<form className="card p-5 mb-6 grid gap-3" onSubmit={email}><h2 className="text-lg font-semibold">Email linesheet</h2><input className="field" name="to" type="email" placeholder="Recipient email" required/><input className="field" name="cc" type="text" placeholder="CC (optional)"/><input className="field" name="bcc" type="text" placeholder="BCC (optional)"/><input className="field" name="subject" defaultValue={s.name||s.linesheet_number} required/><textarea className="field" name="body" rows={4} defaultValue={`Please find the ${s.name||s.linesheet_number} attached.`}/><select className="field" name="attachments" defaultValue="both"><option value="both">Excel and PDF</option><option value="excel">Excel only</option><option value="pdf">PDF only</option></select>{emailError&&<div className="alert-error">{emailError}</div>}<div className="flex gap-2"><button className="button" disabled={sending}>{sending?'Sending…':'Send email'}</button><button type="button" className="button button-secondary" onClick={()=>setEmailOpen(false)}>Cancel</button></div></form>}
    <form className="card p-5 mb-6 flex flex-wrap gap-3 items-end" onSubmit={share}><label className="text-sm font-semibold flex-1 min-w-64">Share recipient<input className="field mt-2" name="recipient" placeholder="Client email or recipient name" required/></label><button className="button">Record recipient</button></form><div className="table-wrap"><table><thead><tr><th>Image</th><th>Product code</th><th>Description</th><th>Color</th><th>Set of</th><th>Sizes</th><th>MRP</th><th>Linesheet SKU</th></tr></thead><tbody>{s.items.map((x:any,i:number)=><tr key={`${x.linesheet_sku||x.sku}-${i}`}><td>{x.images?.length?'Available':'—'}</td><td className="font-semibold">{x.product_code||x.vendor_code||'—'}</td><td>{x.description||x.product_name||'—'}</td><td>{x.color}</td><td>{x.set_of||x.component_count||1}</td><td>{(x.sizes||Object.keys(x.size_quantities||{})).join(', ')}</td><td>{x.mrp||x.unit_price}</td><td className="font-mono text-xs">{x.linesheet_sku||x.sku}</td></tr>)}</tbody></table></div>{data.related_order&&<Link className="card p-5 mt-6 block" href={`/orders/${data.related_order._id}`}>Related PO: <b>{data.related_order.po_number}</b> →</Link>}</>;
}
