'use client';
import { FormEvent, useCallback, useEffect, useState } from 'react';
import Link from 'next/link';
import { api } from '@/lib/api';
import { PageHeading } from '@/components/page-heading';
import { Empty, ErrorState, Loading } from '@/components/states';

export type Column = { key: string; label: string; format?: (value: unknown, row: Record<string, unknown>) => React.ReactNode };

export function OperationalListPage({eyebrow,title,description,endpoint,columns,emptyTitle,relatedHref,relatedLabel,filters=[]}:{eyebrow:string;title:string;description:string;endpoint:string;columns:Column[];emptyTitle:string;relatedHref:string;relatedLabel:string;filters?:{name:string;label:string;options:string[]}[]}){
  const [items,setItems]=useState<Record<string,unknown>[]>([]); const [loading,setLoading]=useState(true); const [error,setError]=useState(''); const [query,setQuery]=useState(''); const [filterValues,setFilterValues]=useState<Record<string,string>>({});
  const load=useCallback(()=>{setLoading(true);setError('');const params=new URLSearchParams();if(query.trim())params.set('q',query.trim());Object.entries(filterValues).forEach(([k,v])=>v&&params.set(k,v));const separator=endpoint.includes('?')?'&':'?';api<{items:Record<string,unknown>[]}>(`${endpoint}${params.toString()?separator+params:''}`).then(x=>setItems(x.items)).catch(e=>setError(e.message)).finally(()=>setLoading(false))},[endpoint,query,filterValues]);
  useEffect(()=>{void load()},[load]);
  function submit(e:FormEvent){e.preventDefault();void load()}
  return <><PageHeading eyebrow={eyebrow} title={title} description={description} action={<Link className="button button-secondary" href={relatedHref}>← {relatedLabel}</Link>}/><form onSubmit={submit} className="card p-4 mb-6 flex flex-col md:flex-row gap-3"><input className="field md:max-w-sm" value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search records" aria-label={`Search ${title}`}/>{filters.map(filter=><select key={filter.name} className="field md:max-w-xs" value={filterValues[filter.name]||''} onChange={e=>setFilterValues(v=>({...v,[filter.name]:e.target.value}))}><option value="">All {filter.label}</option>{filter.options.map(x=><option key={x} value={x}>{x.replaceAll('_',' ')}</option>)}</select>)}<button className="button">Apply filters</button></form>{error?<ErrorState message={error} retry={load}/>:loading?<Loading/>:items.length===0?<Empty title={emptyTitle} detail="No database records match the current filters."/>:<div className="table-wrap"><table><thead><tr>{columns.map(c=><th key={c.key}>{c.label}</th>)}</tr></thead><tbody>{items.map((row,index)=><tr key={String(row._id||index)}>{columns.map(c=><td key={c.key}>{c.format?c.format(row[c.key],row):String(row[c.key]??'—')}</td>)}</tr>)}</tbody></table></div>}</>
}

export const orderColumns:Column[]=[{key:'po_number',label:'PO number',format:(v,row)=><Link className="font-semibold underline underline-offset-4" href={`/orders/${row._id}`}>{String(v)}</Link>},{key:'client_name',label:'Client'},{key:'order_type',label:'Order type',format:v=>String(v||'').replaceAll('_',' ')},{key:'total_quantity',label:'Quantity'},{key:'status',label:'Commercial status',format:v=><span className="status">{String(v||'').replaceAll('_',' ')}</span>},{key:'production_status',label:'Production',format:v=><span className="status">{String(v||'').replaceAll('_',' ')}</span>}];
export const clientColumns:Column[]=[{key:'name',label:'Client'},{key:'client_code',label:'Code'},{key:'category',label:'Category'},{key:'business_types',label:'Business',format:v=>Array.isArray(v)?v.join(', '):'—'},{key:'contact_person',label:'Contact'},{key:'status',label:'Status',format:v=><span className="status">{String(v)}</span>}];
export const productionColumns:Column[]=[{key:'po_number',label:'PO number'},{key:'client_name',label:'Client'},{key:'sku',label:'SKU'},{key:'color',label:'Color'},{key:'size',label:'Size'},{key:'quantity',label:'Quantity'},{key:'current_stage',label:'Stage',format:v=><span className="status">{String(v||'').replaceAll('_',' ')}</span>},{key:'expected_completion_date',label:'Expected'}];
export const stockColumns:Column[]=[{key:'sku',label:'SKU'},{key:'color',label:'Color'},{key:'size',label:'Size'},{key:'location',label:'Location'},{key:'physical',label:'Physical'},{key:'reserved',label:'Reserved'},{key:'available',label:'Available'},{key:'consignment',label:'Consignment'}];
