'use client';

import { FormEvent, useCallback, useEffect, useMemo, useState } from 'react';
import { api } from '@/lib/api';
import { PageHeading } from '@/components/page-heading';

type Role = 'admin' | 'staff' | 'customer';
type User = { id:string; displayName?:string; username?:string; email?:string; role:Role; isActive:boolean; createdAt?:string; lastLoginAt?:string };
type AuditItem = { _id:string; action:string; created_at:string; user_email?:string; details?:Record<string,unknown> };
const blank = { firstName:'', lastName:'', username:'', email:'', role:'staff' as Role, password:'', isActive:true };
const when = (value?:string) => value ? new Date(value).toLocaleString() : 'Never';

export function UserManagement() {
  const [users,setUsers]=useState<User[]>([]), [loading,setLoading]=useState(true), [error,setError]=useState(''), [notice,setNotice]=useState('');
  const [query,setQuery]=useState(''), [role,setRole]=useState<'all'|Role>('all'), [status,setStatus]=useState<'all'|'active'|'inactive'>('all');
  const [showCreate,setShowCreate]=useState(false), [form,setForm]=useState(blank), [saving,setSaving]=useState('');
  const [resetUser,setResetUser]=useState<User|null>(null), [resetPassword,setResetPassword]=useState(''); const [deleteUser,setDeleteUser]=useState<User|null>(null);
  const [auditUser,setAuditUser]=useState<User|null>(null), [auditItems,setAuditItems]=useState<AuditItem[]>([]);
  const load=useCallback(async()=>{setLoading(true);setError('');try{setUsers((await api<{users:User[]}>('/users')).users)}catch(e){setError(e instanceof Error?e.message:'Unable to load users.')}finally{setLoading(false)}},[]);
  useEffect(()=>{void load()},[load]);
  const visible=useMemo(()=>users.filter(user=>{const text=`${user.displayName||''} ${user.username||''} ${user.email||''}`.toLowerCase();return (!query||text.includes(query.toLowerCase()))&&(role==='all'||user.role===role)&&(status==='all'||user.isActive===(status==='active'))}),[users,query,role,status]);
  const totals={total:users.length,active:users.filter(x=>x.isActive).length,inactive:users.filter(x=>!x.isActive).length,admins:users.filter(x=>x.role==='admin').length,staff:users.filter(x=>x.role==='staff').length};
  async function create(event:FormEvent){event.preventDefault();setSaving('create');setError('');try{await api('/users',{method:'POST',body:JSON.stringify(form)});setForm(blank);setShowCreate(false);setNotice('RK-STOCK user created. The temporary password must be changed at first login.');await load()}catch(e){setError(e instanceof Error?e.message:'Unable to create user.')}finally{setSaving('')}}
  async function update(user:User,action:'role'|'status',payload:object){setSaving(user.id);setError('');try{await api(`/users/${user.id}/${action}`,{method:'PATCH',body:JSON.stringify(payload)});setNotice('User updated.');await load()}catch(e){setError(e instanceof Error?e.message:'Unable to update user.')}finally{setSaving('')}}
  async function reset(event:FormEvent){event.preventDefault();if(!resetUser)return;setSaving(resetUser.id);setError('');try{await api(`/users/${resetUser.id}/password`,{method:'PATCH',body:JSON.stringify({password:resetPassword})});setResetUser(null);setResetPassword('');setNotice('Temporary password set and existing sessions revoked.')}catch(e){setError(e instanceof Error?e.message:'Unable to reset password.')}finally{setSaving('')}}
  async function openAudit(user:User){setAuditUser(user);setAuditItems([]);setError('');try{setAuditItems((await api<{items:AuditItem[]}>(`/users/${user.id}/audit`)).items)}catch(e){setError(e instanceof Error?e.message:'Unable to load audit history.')}}
  async function removeUser(){if(!deleteUser)return;setSaving(deleteUser.id);setError('');try{await api(`/users/${deleteUser.id}`,{method:'DELETE'});setDeleteUser(null);setNotice('Inactive user deleted. Historical business records were preserved.');await load()}catch(e){setError(e instanceof Error?e.message:'Unable to delete user.')}finally{setSaving('')}}
  return <>
    <PageHeading eyebrow="Administration" title="Users & roles" description="Manage local RK-STOCK operational identities, roles and access." action={<button className="button" onClick={()=>setShowCreate(true)}>Add user</button>}/>
    <div className="grid grid-cols-2 gap-3 md:grid-cols-5 mb-6">{Object.entries(totals).map(([label,value])=><div className="card p-4" key={label}><div className="font-display text-3xl">{value}</div><div className="eyebrow mt-1">{label}</div></div>)}</div>
    <div className="card p-4 mb-6 grid gap-3 md:grid-cols-[1fr_180px_180px_auto]"><input className="field" value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search name, username or email"/><select className="field" value={role} onChange={e=>setRole(e.target.value as typeof role)}><option value="all">All roles</option><option value="admin">Admin</option><option value="staff">Staff</option><option value="customer">Customer</option></select><select className="field" value={status} onChange={e=>setStatus(e.target.value as typeof status)}><option value="all">All statuses</option><option value="active">Active</option><option value="inactive">Inactive</option></select><button className="button button-secondary" onClick={()=>void load()}>Refresh</button></div>
    {error&&<div className="card border-red-200 bg-red-50 text-red-800 mb-5" role="alert">{error}</div>}{notice&&<div className="card border-green-200 bg-green-50 text-green-800 mb-5">{notice}</div>}
    {showCreate&&<form className="card p-6 mb-6" onSubmit={create}><div className="flex justify-between"><h2 className="font-display text-2xl">Add RK-STOCK user</h2><button type="button" onClick={()=>setShowCreate(false)}>Cancel</button></div><div className="grid md:grid-cols-2 gap-4 mt-5"><label>First name<input required className="field mt-1" value={form.firstName} onChange={e=>setForm({...form,firstName:e.target.value})}/></label><label>Last name<input className="field mt-1" value={form.lastName} onChange={e=>setForm({...form,lastName:e.target.value})}/></label><label>Username<input required className="field mt-1" value={form.username} onChange={e=>setForm({...form,username:e.target.value})}/></label><label>Email<input required type="email" className="field mt-1" value={form.email} onChange={e=>setForm({...form,email:e.target.value})}/></label><label>Role<select className="field mt-1" value={form.role} onChange={e=>setForm({...form,role:e.target.value as Role})}><option value="staff">Staff</option><option value="admin">Admin</option></select></label><label>Temporary password<input required minLength={8} type="password" autoComplete="new-password" className="field mt-1" value={form.password} onChange={e=>setForm({...form,password:e.target.value})}/></label></div><label className="mt-4 flex gap-2"><input type="checkbox" checked={form.isActive} onChange={e=>setForm({...form,isActive:e.target.checked})}/> Active</label><button disabled={saving==='create'} className="button mt-5">{saving==='create'?'Creating…':'Create user'}</button></form>}
    <div className="table-wrap"><table><thead><tr><th>Name</th><th>Username</th><th>Email</th><th>Role</th><th>Status</th><th>Last login</th><th>Created</th><th>Actions</th></tr></thead><tbody>{visible.map(user=><tr key={user.id}><td>{user.displayName||'Unnamed'}</td><td>{user.username?`@${user.username}`:'—'}</td><td>{user.email||'—'}</td><td><select className="field min-w-28" value={user.role} disabled={saving===user.id||user.role==='customer'} onChange={e=>void update(user,'role',{role:e.target.value})}><option value="admin">Admin</option><option value="staff">Staff</option>{user.role==='customer'&&<option value="customer">Customer</option>}</select></td><td><span className="status">{user.isActive?'Active':'Inactive'}</span></td><td>{when(user.lastLoginAt)}</td><td>{when(user.createdAt)}</td><td><div className="flex gap-3"><button className="text-xs underline" disabled={saving===user.id} onClick={()=>void update(user,'status',{isActive:!user.isActive})}>{user.isActive?'Deactivate':'Activate'}</button>{user.role!=='customer'&&<button className="text-xs underline" onClick={()=>setResetUser(user)}>Reset password</button>}{!user.isActive&&<button className="text-xs text-red-700 underline" disabled={saving===user.id} onClick={()=>setDeleteUser(user)}>Delete</button>}<button className="text-xs underline" onClick={()=>void openAudit(user)}>History</button></div></td></tr>)}</tbody></table>{!loading&&visible.length===0&&<div className="p-8 text-center text-stone-500">No users match these filters.</div>}</div>
    {auditUser&&<div className="fixed inset-0 z-50 grid place-items-center bg-black/40 p-4"><div className="card p-6 w-full max-w-2xl max-h-[80vh] overflow-auto"><div className="flex justify-between"><div><h2 className="font-display text-2xl">Audit history</h2><p className="secondary-copy mt-1">{auditUser.email}</p></div><button onClick={()=>setAuditUser(null)}>Close</button></div><div className="mt-5 space-y-3">{auditItems.length?auditItems.map(item=><div key={item._id} className="border-b border-stone-200 pb-3"><div className="font-semibold">{item.action.replaceAll('_',' ')}</div><div className="text-xs text-stone-500">{when(item.created_at)} · {item.user_email||'System'}</div></div>):<p className="secondary-copy">No audit activity recorded.</p>}</div></div></div>}
    {resetUser&&<form onSubmit={reset} className="fixed inset-0 z-50 grid place-items-center bg-black/40 p-4"><div className="card p-6 w-full max-w-md"><h2 className="font-display text-2xl">Reset password</h2><p className="secondary-copy mt-2">Set a temporary RK-STOCK password for {resetUser.email}. Existing local sessions will be revoked.</p><input required minLength={8} type="password" autoComplete="new-password" className="field mt-5" value={resetPassword} onChange={e=>setResetPassword(e.target.value)}/><div className="flex gap-3 mt-5"><button className="button" disabled={saving===resetUser.id}>Reset</button><button type="button" className="button button-secondary" onClick={()=>setResetUser(null)}>Cancel</button></div></div></form>}
    {deleteUser&&<div className="fixed inset-0 z-50 grid place-items-center bg-black/40 p-4"><div className="card p-6 w-full max-w-md"><h2 className="font-display text-2xl">Delete this inactive user permanently?</h2><p className="secondary-copy mt-2">{deleteUser.email} will no longer be able to sign in. The account will be removed, while historical business records remain.</p><div className="flex gap-3 mt-5"><button className="button bg-red-700 hover:bg-red-800" disabled={saving===deleteUser.id} onClick={()=>void removeUser()}>{saving===deleteUser.id?'Deleting…':'Delete permanently'}</button><button className="button button-secondary" onClick={()=>setDeleteUser(null)}>Cancel</button></div></div></div>}
  </>;
}
